#!/bin/bash

hello=ho02123ware38384you443d34o3434ingtod38384ay
re='(.*)[0-9]+(.*)'
while [[ $hello =~ $re ]]; do
  hello=${BASH_REMATCH[1]}${BASH_REMATCH[2]}
done
echo "$hello"


hello=ho02123ware38384you443d34o3434ingtod38384day
re='(.*)[0-9]+(.*)'
while [[ $hello =~ $re ]]; do
  hello=${BASH_REMATCH[1]}${BASH_REMATCH[2]}
done
echo "$hello"




function filemod(){
  cat $1 > file
  re='(.*)[0-9]+(.*)'
  while [[ $hello =~ $re ]]; do
    hello=${BASH_REMATCH[1]}${BASH_REMATCH[2]}
  done

}





find . -name '*.hxx' -exec sed 's/(.*)Handle\((.+)\)(.*)/\1std\:\:shared_ptr\<\2\>\3/g' {} \;




